@persongroup = visitors
@apiUrl = westeurope.api.cognitive.microsoft.com/face/v1.0

### Create persongroup
PUT https://{{apiUrl}}/persongroups/{{persongroup}} HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{faceApiSubscriptionKey}}

{
    "name": "{{persongroup}}",
    "recognitionModel": "recognition_01"
}

################################ END ################################













############################### TESTS ###############################
### Detect face
# @name face
POST https://{{apiUrl}}/detect?returnFaceId=true&returnFaceLandmarks=false&recognitionModel=recognition_01&returnRecognitionModel=false&detectionModel=detection_01 HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{faceApiSubscriptionKey}}

{
    "url": "{{faceImageUrl}}"
}

### Update faceIds with result from previous call ###
### Identify face
POST https://{{apiUrl}}/identify HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{faceApiSubscriptionKey}}

{
    "personGroupId": "{{persongroup}}",
    "faceIds": [
        "4f6e1517-aad6-489f-beec-236a72204f0b"
    ],
    "maxNumOfCandidatesReturned": 1,
    "confidenceThreshold": 0.5
}

### Get persons
GET https://{{apiUrl}}/persongroups/{{persongroup}}/persons HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{faceApiSubscriptionKey}}

### Delete person by ID
DELETE https://{{apiUrl}}/persongroups/{{persongroup}}/persons/ed7f5a87-b223-4e01-b5f5-74bfad5f1fde HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{faceApiSubscriptionKey}}

### Create person in persongroup
# @name person
POST https://{{apiUrl}}/persongroups/{{persongroup}}/persons HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{faceApiSubscriptionKey}}

{
    "name": "Eldert Grootenboer"
}

### Train person group
POST https://{{apiUrl}}/persongroups/{{persongroup}}/train HTTP/1.1
Ocp-Apim-Subscription-Key: {{faceApiSubscriptionKey}}

### Get training status
GET https://{{apiUrl}}/persongroups/{{persongroup}}/training HTTP/1.1
Ocp-Apim-Subscription-Key: {{faceApiSubscriptionKey}}

### Add face to person
POST https://{{apiUrl}}/persongroups/{{persongroup}}/persons/{{person.response.body.personId}}/persistedFaces?detectionModel=detection_01 HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{faceApiSubscriptionKey}}

{
    "url": "{{faceImageUrl}}"
}